
version: '3'

services:

  canchas:
    build:
      context: ./services/canchas
      dockerfile: Dockerfile-dev
    volumes:
      - './services/canchas:/can/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@canchas-db:5432/canchas_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@canchas-db:5432/canchas_test
    depends_on:
      - canchas-db

  canchas-db:
    build:
      context: ./services/canchas/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - canchas

